apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-techdocs
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    backstage.io/techdocs-ref: dir:./docs
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
